"""
Dunyoning eng chiroyli tabiiy joylari ro'yxati.
Har bir yozuv: nomi, davlati, va rasm/video qidiruv uchun query (inglizcha, Pexels/Wikipedia uchun qulay).
Botga yangi joy qo'shish uchun shunchaki quyidagi ro'yxatga yangi dict qo'shing.
"""

PLACES = [
    {"name": "Plitvice ko'llari", "country": "Xorvatiya", "query": "Plitvice Lakes Croatia"},
    {"name": "Ha Long ko'rfazi", "country": "Vetnam", "query": "Ha Long Bay Vietnam"},
    {"name": "Fiordland Milliy Bog'i", "country": "Yangi Zelandiya", "query": "Fiordland New Zealand"},
    {"name": "Torres del Paine", "country": "Chili", "query": "Torres del Paine Chile"},
    {"name": "Sahroi Kabir", "country": "Shimoliy Afrika", "query": "Sahara Desert dunes"},
    {"name": "Amazonka o'rmoni", "country": "Braziliya", "query": "Amazon rainforest"},
    {"name": "Katta Bar'er rifi", "country": "Avstraliya", "query": "Great Barrier Reef"},
    {"name": "Janszyatse tog'lari", "country": "Xitoy", "query": "Zhangjiajie China"},
    {"name": "Banff Milliy Bog'i", "country": "Kanada", "query": "Banff National Park Canada"},
    {"name": "Iguasu sharshara", "country": "Argentina/Braziliya", "query": "Iguazu Falls"},
    {"name": "Viktoriya sharshara", "country": "Zambiya/Zimbabve", "query": "Victoria Falls"},
    {"name": "Antelope kanyoni", "country": "AQSH", "query": "Antelope Canyon USA"},
    {"name": "Salar de Uyuni", "country": "Boliviya", "query": "Salar de Uyuni Bolivia salt flat"},
    {"name": "Farer orollari", "country": "Daniya", "query": "Faroe Islands"},
    {"name": "Lofoten orollari", "country": "Norvegiya", "query": "Lofoten Islands Norway"},
    {"name": "Jiuzhaigou vodiysi", "country": "Xitoy", "query": "Jiuzhaigou Valley China"},
    {"name": "Meteora", "country": "Gretsiya", "query": "Meteora Greece monasteries"},
    {"name": "Kappadokiya", "country": "Turkiya", "query": "Cappadocia Turkey balloons"},
    {"name": "Sokotra oroli", "country": "Yaman", "query": "Socotra Island Yemen"},
    {"name": "Yellowstone Milliy Bog'i", "country": "AQSH", "query": "Yellowstone National Park"},
    {"name": "Grand Kanyon", "country": "AQSH", "query": "Grand Canyon Arizona"},
    {"name": "Yosemite Milliy Bog'i", "country": "AQSH", "query": "Yosemite National Park"},
    {"name": "Fudziyama tog'i", "country": "Yaponiya", "query": "Mount Fuji Japan"},
    {"name": "Bali sholi teraslari", "country": "Indoneziya", "query": "Bali rice terraces"},
    {"name": "Maldiv orollari", "country": "Maldiv orollari", "query": "Maldives islands aerial"},
    {"name": "Seyshel orollari", "country": "Seyshel orollari", "query": "Seychelles islands beach"},
    {"name": "Table Mountain", "country": "Janubiy Afrika", "query": "Table Mountain Cape Town"},
    {"name": "Katta Ko'k O'ra", "country": "Beliz", "query": "Great Blue Hole Belize"},
    {"name": "Skaftafell", "country": "Islandiya", "query": "Skaftafell Iceland glacier"},
    {"name": "Reynisfjara plyaji", "country": "Islandiya", "query": "Reynisfjara black sand beach Iceland"},
    {"name": "Milford Sound", "country": "Yangi Zelandiya", "query": "Milford Sound New Zealand"},
    {"name": "Bryce Kanyoni", "country": "AQSH", "query": "Bryce Canyon Utah"},
    {"name": "Zion Milliy Bog'i", "country": "AQSH", "query": "Zion National Park"},
    {"name": "Denali", "country": "AQSH (Alyaska)", "query": "Denali Alaska mountain"},
    {"name": "Serengeti", "country": "Tanzaniya", "query": "Serengeti savanna wildlife"},
    {"name": "Okavango deltasi", "country": "Botsvana", "query": "Okavango Delta Botswana"},
    {"name": "Anxel sharshara", "country": "Venesuela", "query": "Angel Falls Venezuela"},
    {"name": "Perito Moreno muzligi", "country": "Argentina", "query": "Perito Moreno Glacier"},
    {"name": "Uluru", "country": "Avstraliya", "query": "Uluru Ayers Rock Australia"},
    {"name": "Pamukkale", "country": "Turkiya", "query": "Pamukkale Turkey travertines"},
    {"name": "Krka Milliy Bog'i", "country": "Xorvatiya", "query": "Krka National Park Croatia"},
    {"name": "Trolltunga", "country": "Norvegiya", "query": "Trolltunga Norway cliff"},
    {"name": "Preikestolen", "country": "Norvegiya", "query": "Preikestolen Pulpit Rock Norway"},
    {"name": "Radja Ampat", "country": "Indoneziya", "query": "Raja Ampat Indonesia islands"},
    {"name": "Palavan oroli", "country": "Filippin", "query": "Palawan Philippines lagoon"},
    {"name": "Komodo oroli", "country": "Indoneziya", "query": "Komodo Island Indonesia"},
    {"name": "Chinkve Terre", "country": "Italiya", "query": "Cinque Terre Italy coast"},
    {"name": "Amalfi qirg'og'i", "country": "Italiya", "query": "Amalfi Coast Italy"},
    {"name": "Provans lavanda dalalari", "country": "Fransiya", "query": "Provence lavender fields France"},
    {"name": "Shotlandiya tog'lari", "country": "Buyuk Britaniya", "query": "Scottish Highlands"},
    {"name": "Qora o'rmon", "country": "Germaniya", "query": "Black Forest Germany"},
    {"name": "Danakil botig'i", "country": "Efiopiya", "query": "Danakil Depression Ethiopia"},
    {"name": "Namib sahrosi", "country": "Namibiya", "query": "Namib Desert dunes"},
    {"name": "Buyuk Okean yo'li", "country": "Avstraliya", "query": "Great Ocean Road Australia"},
    {"name": "Uaythevn plyaji", "country": "Avstraliya", "query": "Whitehaven Beach Australia"},
    {"name": "Bora-Bora", "country": "Frantsiya Polineziyasi", "query": "Bora Bora island lagoon"},
    {"name": "Ngorongoro krateri", "country": "Tanzaniya", "query": "Ngorongoro Crater Tanzania"},
    {"name": "Kilimanjaro tog'i", "country": "Tanzaniya", "query": "Mount Kilimanjaro"},
    {"name": "Annapurna", "country": "Nepal", "query": "Annapurna Nepal mountains"},
    {"name": "Ladakh", "country": "Hindiston", "query": "Ladakh India mountains"},
    {"name": "Kerala kanallari", "country": "Hindiston", "query": "Kerala backwaters India"},
    {"name": "Jeju oroli", "country": "Janubiy Koreya", "query": "Jeju Island South Korea"},
    {"name": "Xokkaydo", "country": "Yaponiya", "query": "Hokkaido Japan landscape"},
    {"name": "Big Sur", "country": "AQSH", "query": "Big Sur California coast"},
    {"name": "Sekvoyya o'rmoni", "country": "AQSH", "query": "Redwood Forest California"},
    {"name": "Glacier Milliy Bog'i", "country": "AQSH", "query": "Glacier National Park Montana"},
    {"name": "Niagara sharshara", "country": "AQSH/Kanada", "query": "Niagara Falls"},
    {"name": "Blue Ridge tog'lari", "country": "AQSH", "query": "Blue Ridge Mountains"},
    {"name": "Great Smoky Mountains", "country": "AQSH", "query": "Great Smoky Mountains"},
]
